services:
  pgvector:
    image: 'pgvector/pgvector:0.8.0-pg17'
    environment:
      - 'POSTGRES_DB=restaurant_recommender'
      - 'POSTGRES_PASSWORD=pwd'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
    pgvector-data: